import SideBar from "@/components/admin/ui/side-bar";
import { Metadata } from "next";
import React from "react";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full h-screen bg-[#EDEDED] p-4 flex">
      <SideBar />
      <main className="flex-1 ml-8 h-full overflow-y-auto bg-white rounded-xl p-4">
        {children}
      </main>
      <Toaster position="top-right" reverseOrder={true} />
    </section>
  );
}

export default layout;
